
services:

  backend:
    build: ./Computer_shop_backend 
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysql
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_PASSWORD=$MYSQLDB_PASWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT



  mysql:
    image: mysql:latest
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASWORD=$MYSQLDB_ROOT_PASWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
volumes:
  db_data:
