
services:

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
    networks:
      - app-network

  backend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-ElFonsi.git
      dockerfile: Computer_shop_backend/Dockerfile
    working_dir: /app/Computer_shop_backend
    ports:
      - "8080:8080"
    environment:
      - MYSQLDB_HOST=mysql
      - MYSQLDB_PASSWORD=1234
      - MYSQLDB_DATABASE=db
    depends_on:
      - mysql
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-ElFonsi.git
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
