
services:

  backend:
    build: ./Computer_shop_backend 
    env_file: ./.env
    restart: always
      
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysql
    environment:
      - MYSQLDB_HOST=mysql
      - MYSQLDB_PASSWORD=1234
      - MYSQLDB_DATABASE=db
      - MYSQLDB_DOCKER_PORT=3306

  mysql:
    image: mysql:latest
    env_file: ./.env
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
        - MYSQL_PASSWORD=1234
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_DATABASE=db
volumes:
  db_data:
