
services:

  backend:
    build: ./Computer_shop_backend 
    ports:
      - "8080:8080" 
    depends_on:
      - mysql
    environment:
      - DB_HOST=db


  mysql:
    image: mysql:latest
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
volumes:
  db_data:
