# nginx/Dockerfile
FROM nginx:latest

# Copia el archivo de configuración personalizado a la ubicación predeterminada de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para las solicitudes HTTP
EXPOSE 80
